[meta_properties]
id = "2541b0b9c4350984"
asset_kind = "Animation"

[asset_properties]
frame_size = [49, 49]
frame_len = 4
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
