[meta_properties]
id = "9d0af55697fec54e"
asset_kind = "Animation"

[asset_properties]
frame_size = [40, 34]
frame_len = 14
duration = [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.8]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 24.0
