[meta_properties]
id = "a43cb91a18b4feb7"
asset_kind = "Animation"

[asset_properties]
frame_size = [40, 34]
frame_len = 4
duration = [0.2, 1.2, 0.2, 0.8]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 24.0
