[meta_properties]
id = "6cd85572aed64f83"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 32]
frame_len = 13
duration = 0.15
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 21.0
