[meta_properties]
id = "a7793dea16c9327d"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 32]
frame_len = 13
duration = [0.15, 0.2, 0.2, 0.2, 0.2, 0.2, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15]
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 21.0
