[meta_properties]
id = "4fdb5f9af75d4354"
asset_kind = "Animation"

[asset_properties]
frame_size = [22, 22]
frame_len = 4
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
