[meta_properties]
id = "ccdd30a80e070cb1"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 80]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 78.0
