[meta_properties]
id = "95f52a4a3996b550"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 3
duration = [0.2, 0.1, 0.4]
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 30.0
