[meta_properties]
id = "62ae2b67c97776c7"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 56]
frame_len = 8
duration = 0.125
atlas = "Default"

[asset_properties.offset]
horizontal = 24.0
vertical = 48.0
