[meta_properties]
id = "a06f07a515bd93f"
asset_kind = "Animation"

[asset_properties]
frame_size = [104, 48]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = 48.0
vertical = 24.0
