[meta_properties]
id = "d2bdab9f5c4abb22"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 104]
frame_len = 4
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 24.0
vertical = 88.0
