[meta_properties]
id = "8004e8317bbce816"
asset_kind = "Animation"

[asset_properties]
frame_size = [49, 39]
frame_len = 4
duration = 0.15
atlas = "Default"

[asset_properties.offset]
horizontal = 24.0
vertical = 21.0
