[meta_properties]
id = "c2fda26b106ed872"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 4
duration = 0.15
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 30.0
