[meta_properties]
id = "512341011a2d94b2"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 4
duration = [0.8, 0.125, 0.125, 0.125]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 30.0
