[meta_properties]
id = "66ceb6f58d9a5595"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 3
duration = [0.075, 0.125, 0.075]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 54.0
