[meta_properties]
id = "bcccccf092c668bc"
asset_kind = "Animation"

[asset_properties]
frame_size = [128, 48]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = 64.0
vertical = 15.0
