[meta_properties]
id = "90661f56cd4f72e1"
asset_kind = "Animation"

[asset_properties]
frame_size = [64, 48]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = 32.0
vertical = 28.0
