[meta_properties]
id = "cd4b32c20d2e85ad"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 4
duration = [0.075, 0.075, 0.075, 0.125]
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 30.0
