[meta_properties]
id = "a01149cdd290ae06"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 3
duration = [0.2, 0.25, 0.4]
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 30.0
