[meta_properties]
id = "793327c995686cfe"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 32]
frame_len = 7
duration = 0.05
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 22.0
