[meta_properties]
id = "8fb391a51b85d646"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 19
duration = [0.1, 0.1, 0.1, 0.075, 0.075, 0.075, 0.075, 0.075, 0.075, 0.075, 0.075, 0.075, 0.075, 0.1, 0.1, 0.1, 0.1, 0.1, 1.4]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 32.0
