[meta_properties]
id = "b46cbaddf376484c"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 8
duration = [0.2, 0.1, 0.2, 0.2, 0.1, 0.2, 0.2, 0.1]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 32.0
