[meta_properties]
id = "6a0c7e28015a9ee5"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 4
duration = 0.125
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 32.0
