[meta_properties]
id = "9b4163e59a184e5c"
asset_kind = "Animation"

[asset_properties]
frame_size = [40, 56]
frame_len = 2
duration = 0.075
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 45.0
