[meta_properties]
id = "54ceaa4d50a7be16"
asset_kind = "Animation"

[asset_properties]
frame_size = [24, 24]
frame_len = 4
duration = [0.1, 0.1, 0.1, 1.0]
atlas = "UI"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
