[meta_properties]
id = "9e3a90884fa09629"
asset_kind = "Animation"

[asset_properties]
frame_size = [24, 24]
frame_len = 5
duration = [0.3, 0.3, 0.3, 0.3, 0.1]
atlas = "UI"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
