[meta_properties]
id = "5411b69e35b3e33"
asset_kind = "Animation"

[asset_properties]
frame_size = [24, 24]
frame_len = 2
duration = 0.4
atlas = "UI"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
