[meta_properties]
id = "8f5458603041a8f8"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 32]
frame_len = 2
duration = 0.2
atlas = "UI"

[asset_properties.offset]
horizontal = 16.0
vertical = 16.0
