[meta_properties]
id = "7ac53393bf1682f9"
asset_kind = "Animation"

[asset_properties]
frame_size = [24, 24]
frame_len = 3
duration = [0.1, 0.1, 1.0]
atlas = "UI"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
