[meta_properties]
id = "f9eaf7ac4046ccf7"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 56]
frame_len = 4
duration = [0.15, 0.15, 0.15, 0.1]
atlas = "Default"

[asset_properties.offset]
horizontal = 24.0
vertical = 48.0
