[meta_properties]
id = "c9def7a6cda39f33"
asset_kind = "Animation"

[asset_properties]
frame_size = [13, 9]
frame_len = 17
duration = [0.1, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
atlas = "UI"
