[meta_properties]
id = "cb7df071dd5925b8"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 56]
frame_len = 3
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 32.0
