[meta_properties]
id = "b071d53eb26610cf"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 32]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = "Left"
vertical = 8.0
