[meta_properties]
id = "2e69a7ed3a47ad7d"
asset_kind = "Animation"

[asset_properties]
frame_size = [40, 48]
frame_len = 16
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 33.0
