[meta_properties]
id = "5cccdda5039f1e0a"
asset_kind = "Animation"

[asset_properties]
frame_size = [56, 56]
frame_len = 4
duration = 0.15
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 46.0
