[meta_properties]
id = "8d67ff8cfb8db76b"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 64]
frame_len = 11
duration = [0.15, 0.15, 0.125, 0.15, 0.2, 0.15, 0.15, 0.2, 0.15, 0.15, 0.6]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 48.0
