[meta_properties]
id = "da4f823bcc8e37c4"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 64]
frame_len = 6
duration = 0.075
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 48.0
