[meta_properties]
id = "5420ba3d9fa20c31"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 4
duration = [0.15, 0.15, 0.8, 0.15]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 54.0
