[meta_properties]
id = "831d7f9b52dbe8"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 56]
frame_len = 3
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 32.0
