[meta_properties]
id = "263f67a7a5f56af2"
asset_kind = "Animation"

[asset_properties]
frame_size = [64, 64]
frame_len = 4
duration = 0.075
atlas = "Default"

[asset_properties.offset]
horizontal = 32.0
vertical = 38.0
