[meta_properties]
id = "5d59c53a4d1b53ba"
asset_kind = "Animation"

[asset_properties]
frame_size = [64, 64]
frame_len = 3
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 32.0
vertical = 38.0
