[meta_properties]
id = "dfc80666f529e8d3"
asset_kind = "Animation"

[asset_properties]
frame_size = [64, 64]
frame_len = 3
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 32.0
vertical = 38.0
