[meta_properties]
id = "a20dc93c2d37cf20"
asset_kind = "Animation"

[asset_properties]
frame_size = [64, 96]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = 28.0
vertical = 87.0
