[meta_properties]
id = "9e6496a635b43d5b"
asset_kind = "Animation"

[asset_properties]
frame_size = [24, 104]
frame_len = 4
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 8.0
vertical = 92.0
