[meta_properties]
id = "178bf5c726774435"
asset_kind = "Animation"

[asset_properties]
frame_size = [24, 24]
frame_len = 11
duration = [0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 1.1]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
