[meta_properties]
id = "2e975c96541db1da"
asset_kind = "Animation"

[asset_properties]
frame_size = [16, 16]
frame_len = 16
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
