[meta_properties]
id = "2d0d0b6c8b532f9d"
asset_kind = "Animation"

[asset_properties]
frame_size = [40, 40]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = 8.0
vertical = 16.0
