[meta_properties]
id = "860adf9b04baeaa5"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 4
duration = [0.1, 0.125, 0.1, 0.3]
atlas = "Default"

[asset_properties.offset]
horizontal = 40.0
vertical = 54.0
