[meta_properties]
id = "d8755c7a3139898d"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 6
duration = [0.1, 0.2, 0.1, 0.1, 0.1, 0.1]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 54.0
