[meta_properties]
id = "ac95e4f86da7b9e5"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 48]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = 24.0
vertical = 22.0
