[meta_properties]
id = "1819abea7c9578ef"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 48]
frame_len = 12
duration = [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.8]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 30.0
