[meta_properties]
id = "a70c1c7ea1f73df8"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 32]
frame_len = 20
duration = 0.15
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 24.0
