[meta_properties]
id = "48ee9b15543e94"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 32]
frame_len = 18
duration = 0.15
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 24.0
