[meta_properties]
id = "3bf48bc4d28b4566"
asset_kind = "Animation"

[asset_properties]
frame_size = [24, 56]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = 12.0
vertical = 40.0
