[meta_properties]
id = "7bf8015e6a09e59c"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 4
duration = [0.6, 0.1, 1.2, 0.1]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 54.0
