[meta_properties]
id = "dafd3b0383186b40"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 3
duration = [0.075, 0.125, 0.075]
atlas = "Default"

[asset_properties.offset]
horizontal = 40.0
vertical = 54.0
