[meta_properties]
id = "e28900ff922bb9fc"
asset_kind = "Animation"

[asset_properties]
frame_size = [18, 18]
frame_len = 10
duration = [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 1.2]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
