[meta_properties]
id = "76724f56cd955549"
asset_kind = "Animation"

[asset_properties]
frame_size = [18, 18]
frame_len = 10
duration = [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 1.2]
atlas = "UI"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
