[meta_properties]
id = "ee5ba4b2c2324598"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 40]
frame_len = 4
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 31.0
