[meta_properties]
id = "f0e4fd40b9622c83"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 48]
frame_len = 6
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 24.0
vertical = 24.0
