[meta_properties]
id = "6b6ca16c8e0bcbdd"
asset_kind = "Animation"

[asset_properties]
frame_size = [10, 11]
frame_len = 4
duration = [0.2, 0.125, 0.125, 0.125]
atlas = "Default"

[asset_properties.offset]
horizontal = 5.0
vertical = 8.0
