[meta_properties]
id = "b72e0f95b560ca1c"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 4
duration = [3.0, 0.1, 3.0, 0.1]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 54.0
