[meta_properties]
id = "f3fb866920abff5a"
asset_kind = "Animation"

[asset_properties]
frame_size = [14, 14]
frame_len = 6
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
