[meta_properties]
id = "df14f6d53f1d920b"
asset_kind = "Animation"

[asset_properties]
frame_size = [10, 10]
frame_len = 3
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
