[meta_properties]
id = "914e2d1bba09d530"
asset_kind = "Animation"

[asset_properties]
frame_size = [22, 22]
frame_len = 4
duration = [0.1, 0.1, 0.15, 0.1]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
