[meta_properties]
id = "b52ed7c26bb79e50"
asset_kind = "Animation"

[asset_properties]
frame_size = [22, 22]
atlas = "Default"
duration = [0.1]

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
