[meta_properties]
id = "3e36b3c44e07cc6e"
asset_kind = "Animation"

[asset_properties]
frame_size = [56, 56]
frame_len = 8
duration = 0.125
atlas = "Default"

[asset_properties.offset]
horizontal = 28.0
vertical = 46.0
