[meta_properties]
id = "95e06b7226a0b1cc"
asset_kind = "Animation"

[asset_properties]
frame_size = [262, 126]
atlas = "UI"
tags = ["manual-load"]

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
