[meta_properties]
id = "924bc432c735cfb3"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 48]
frame_len = 19
duration = [0.15, 0.2, 0.15, 0.1, 0.1, 0.2, 0.15, 0.1, 0.1, 0.5, 0.1, 0.5, 0.1, 0.25, 0.25, 0.25, 0.25, 0.25, 0.1]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 26.0
