[meta_properties]
id = "809040e66dcba6a7"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 56]
frame_len = 9
duration = [0.4, 0.1, 0.15, 0.1, 0.1, 0.1, 0.1, 0.1, 1.7]
atlas = "Default"

[asset_properties.offset]
horizontal = 24.0
vertical = 48.0
