[meta_properties]
id = "1864f2da34a2462e"
asset_kind = "Animation"

[asset_properties]
frame_size = [24, 24]
frame_len = 4
duration = 0.175
atlas = "Default"

[asset_properties.offset]
horizontal = 12.0
vertical = 14.0
