[meta_properties]
id = "65b597a5270c94e5"
asset_kind = "Animation"

[asset_properties]
frame_size = [24, 24]
frame_len = 5
duration = [0.15, 0.15, 0.25, 0.15, 0.15]
atlas = "Default"

[asset_properties.offset]
horizontal = 12.0
vertical = 14.0
