[meta_properties]
id = "240f2e5f42b0e4fa"
asset_kind = "Animation"

[asset_properties]
frame_size = [24, 24]
frame_len = 8
duration = 0.125
atlas = "Default"

[asset_properties.offset]
horizontal = 12.0
vertical = 14.0
