[meta_properties]
id = "2568a38802be86ec"
asset_kind = "Animation"

[asset_properties]
frame_size = [24, 24]
frame_len = 2
duration = 0.05
atlas = "Default"

[asset_properties.offset]
horizontal = 12.0
vertical = 14.0
