[meta_properties]
id = "24d499f46f06a4a7"
asset_kind = "Animation"

[asset_properties]
frame_size = [24, 24]
frame_len = 2
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = 12.0
vertical = 14.0
