[meta_properties]
id = "cbc164f7d302eb64"
asset_kind = "Animation"

[asset_properties]
frame_size = [24, 24]
frame_len = 2
duration = 0.075
atlas = "Default"

[asset_properties.offset]
horizontal = 12.0
vertical = 14.0
