[meta_properties]
id = "a1135c6eafc0882b"
asset_kind = "Animation"

[asset_properties]
frame_size = [24, 24]
frame_len = 4
duration = 0.075
atlas = "Default"

[asset_properties.offset]
horizontal = 12.0
vertical = 14.0
