[meta_properties]
id = "860a1a0b81fea44b"
asset_kind = "Animation"

[asset_properties]
frame_size = [24, 24]
frame_len = 2
duration = 0.15
atlas = "Default"

[asset_properties.offset]
horizontal = 12.0
vertical = 14.0
