[meta_properties]
id = "9d4730020646701b"
asset_kind = "Animation"

[asset_properties]
frame_size = [24, 24]
frame_len = 4
duration = [2.5, 0.15, 0.1, 0.15]
atlas = "Default"

[asset_properties.offset]
horizontal = 12.0
vertical = 14.0
