[meta_properties]
id = "11f3e48bbfe7681f"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 48]
frame_len = 16
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = 24.0
vertical = 24.0
