[meta_properties]
id = "92ad244b1bb01b7c"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 6
duration = [0.1, 0.1, 0.1, 0.25, 0.1, 0.1]
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 32.0
