[meta_properties]
id = "fe241a81ca1a63fd"
asset_kind = "Animation"

[asset_properties]
frame_size = [64, 80]
frame_len = 4
duration = 0.075
atlas = "Default"

[asset_properties.offset]
horizontal = 32.0
vertical = 48.0
