[meta_properties]
id = "9cb5d8abf11c4a1f"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 9
duration = [0.3, 0.8, 0.3, 3.0, 0.15, 1.5, 0.15, 0.125, 1.5]
atlas = "Default"

[asset_properties.offset]
horizontal = 40.0
vertical = 54.0
