[meta_properties]
id = "f7b88494d8171146"
asset_kind = "Animation"

[asset_properties]
frame_size = [9, 1]
frame_len = 2
duration = 0.025
atlas = "UI"

[asset_properties.offset]
horizontal = 8.0
vertical = "Top"
