[meta_properties]
id = "70f18c3329b3f849"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 56]
frame_len = 4
duration = 0.125
atlas = "Default"

[asset_properties.offset]
horizontal = 24.0
vertical = 48.0
