[meta_properties]
id = "14b2e37324b2f77c"
asset_kind = "Animation"

[asset_properties]
frame_size = [10, 10]
frame_len = 4
duration = 0.15
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
