[meta_properties]
id = "ac0dc73a1ae28ab1"
asset_kind = "Animation"

[asset_properties]
frame_size = [10, 10]
frame_len = 4
duration = 0.15
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
