[meta_properties]
id = "1012e29c1ec88261"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 32]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 19.0
