[meta_properties]
id = "83b03be748af6f06"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 80]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 56.0
