[meta_properties]
id = "f35d924d59471370"
asset_kind = "Animation"

[asset_properties]
frame_size = [96, 96]
frame_len = 19
duration = 0.05
atlas = "Default"

[asset_properties.offset]
horizontal = 48.0
vertical = 48.0
