[meta_properties]
id = "6e9103049939c128"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 8
duration = [0.1, 0.1, 0.1, 0.1, 0.1, 0.15, 0.15, 0.05]
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 32.0
