[meta_properties]
id = "e95cadec78ce2cde"
asset_kind = "Animation"

[asset_properties]
frame_size = [18, 18]
frame_len = 4
duration = 0.3
atlas = "UI"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
