[meta_properties]
id = "eb8a634811326cb"
asset_kind = "Animation"

[asset_properties]
frame_size = [18, 18]
frame_len = 4
duration = 1.2
atlas = "UI"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
