[meta_properties]
id = "e409e4cb7500cfaa"
asset_kind = "Animation"

[asset_properties]
frame_size = [16, 16]
frame_len = 16
duration = 0.025
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
