[meta_properties]
id = "deb0a5b58a3a1fe0"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 4
duration = [0.2, 0.4, 0.2, 0.4]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 32.0
