[meta_properties]
id = "ddeb574a09ad73b1"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 56]
frame_len = 7
duration = [0.1, 0.1, 0.1, 0.1, 0.1, 0.075, 0.15]
atlas = "Default"

[asset_properties.offset]
horizontal = 24.0
vertical = 40.0
