[meta_properties]
id = "e8422f3aa0d75f74"
asset_kind = "Animation"

[asset_properties]
frame_size = [112, 112]
frame_len = 2
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 56.0
vertical = 67.0
