[meta_properties]
id = "c2ed9346cc6b8b11"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 19
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 37.0
vertical = 51.0
