[meta_properties]
id = "feb8626724d56058"
asset_kind = "Animation"

[asset_properties]
frame_size = [40, 32]
frame_len = 5
duration = [0.4, 0.25, 0.2, 0.15, 0.1]
atlas = "Default"

[asset_properties.offset]
horizontal = 20.0
vertical = 16.0
