[meta_properties]
id = "7fde31a9ae1be71f"
asset_kind = "Animation"

[asset_properties]
frame_size = [64, 64]
frame_len = 8
duration = [0.075, 0.075, 0.075, 0.075, 0.1, 0.1, 0.1, 0.3]
atlas = "Default"

[asset_properties.offset]
horizontal = 32.0
vertical = 32.0
