[meta_properties]
id = "4d52b9ccfe2df783"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 4
duration = [0.3, 0.15, 0.3, 0.15]
atlas = "Default"

[asset_properties.offset]
horizontal = 37.0
vertical = 51.0
