[meta_properties]
id = "f792e1239e57957"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 10
duration = 0.075
atlas = "Default"

[asset_properties.offset]
horizontal = 37.0
vertical = 51.0
