[meta_properties]
id = "bda0137cb8a0909b"
asset_kind = "Animation"

[asset_properties]
frame_size = [160, 112]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = 80.0
vertical = 29.0
