[meta_properties]
id = "ba41eda297b3615b"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 56]
frame_len = 6
duration = 0.4
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 55.0
