[meta_properties]
id = "ab3207c2b91c0b83"
asset_kind = "Animation"

[asset_properties]
frame_size = [40, 56]
frame_len = 6
duration = 0.4
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 55.0
