[meta_properties]
id = "bc001d904070ecf1"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 56]
frame_len = 6
duration = 0.4
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 55.0
