[meta_properties]
id = "4f7b22e208ab7dd6"
asset_kind = "Animation"

[asset_properties]
frame_size = [40, 40]
frame_len = 6
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 20.0
vertical = 23.0
