[meta_properties]
id = "7859ce54a9a5e34c"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 32]
frame_len = 4
duration = 0.25
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 16.0
