[meta_properties]
id = "3043d04e421d69ac"
asset_kind = "Animation"

[asset_properties]
frame_size = [40, 40]
frame_len = 6
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 20.0
vertical = 23.0
