[meta_properties]
id = "47781db4a21c1ace"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 3
duration = [0.1, 0.1, 0.4]
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 30.0
