[meta_properties]
id = "4a72d44efc094c0"
asset_kind = "Animation"

[asset_properties]
frame_size = [28, 47]
frame_len = 2
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 14.0
vertical = 24.0
