[meta_properties]
id = "15c8b5dad2b5603b"
asset_kind = "Animation"

[asset_properties]
frame_size = [40, 40]
frame_len = 4
duration = 0.125
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 25.0
