[meta_properties]
id = "323d64d500b00a58"
asset_kind = "Animation"

[asset_properties]
frame_size = [88, 40]
frame_len = 3
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Bottom"
