[meta_properties]
id = "9e2349a120667c3c"
asset_kind = "Animation"

[asset_properties]
frame_size = [56, 56]
frame_len = 4
duration = 0.15
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 46.0
