[meta_properties]
id = "cea2973306e597a5"
asset_kind = "Animation"

[asset_properties]
frame_size = [96, 96]
frame_len = 8
duration = 0.075
atlas = "Default"

[asset_properties.offset]
horizontal = 48.0
vertical = 72.0
