[meta_properties]
id = "31f213a1b9ecbb0a"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 64]
frame_len = 2
duration = [0.1, 0.8]
atlas = "Default"

[asset_properties.offset]
horizontal = 24.0
vertical = 48.0
