[meta_properties]
id = "9b9e379231acfa8"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 64]
frame_len = 7
duration = [0.05, 0.05, 0.05, 0.05, 0.075, 0.075, 0.15]
atlas = "Default"

[asset_properties.offset]
horizontal = 24.0
vertical = 48.0
