[meta_properties]
id = "cb6a2b821fd92ff0"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 8
duration = 0.075
atlas = "Default"

[asset_properties.offset]
horizontal = 40.0
vertical = 54.0
