[meta_properties]
id = "e161f52604a89f1a"
asset_kind = "Animation"

[asset_properties]
frame_size = [64, 48]
frame_len = 7
duration = [0.125, 0.1, 0.075, 0.05, 0.075, 0.1, 0.125]
atlas = "Default"

[asset_properties.offset]
horizontal = 32.0
vertical = 36.0
