[meta_properties]
id = "d20168d3c0e0b0eb"
asset_kind = "Animation"

[asset_properties]
frame_size = [16, 24]
frame_len = 4
duration = 0.125
atlas = "Default"

[asset_properties.offset]
horizontal = 8.0
vertical = 16.0
