[meta_properties]
id = "32462b975f147449"
asset_kind = "Animation"

[asset_properties]
frame_size = [64, 96]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = 32.0
vertical = 72.0
