[meta_properties]
id = "f5b706ba44b2017d"
asset_kind = "Animation"

[asset_properties]
frame_size = [8, 64]
frame_len = 12
duration = [10.0, 0.125, 0.15, 3.5, 0.125, 0.075, 0.2, 0.125, 0.075, 1.2, 0.15, 0.125]
atlas = "Default"

[asset_properties.offset]
horizontal = 4.0
vertical = 63.0
