[meta_properties]
id = "99ec85885fdb0d44"
asset_kind = "Animation"

[asset_properties]
frame_size = [40, 48]
frame_len = 3
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 24.0
