[meta_properties]
id = "1f7cf654a7b01c7f"
asset_kind = "Animation"

[asset_properties]
frame_size = [40, 48]
frame_len = 2
duration = 0.075
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 24.0
