[meta_properties]
id = "1446a2c98b2ca90a"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 8
duration = 0.15
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 30.0
