[meta_properties]
id = "dffaca5e9e4edc1e"
asset_kind = "Animation"

[asset_properties]
frame_size = [24, 47]
frame_len = 6
duration = 0.125
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 45.0
