[meta_properties]
id = "24f686c2a1002b17"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 64]
frame_len = 4
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 23.0
vertical = 53.0
