[meta_properties]
id = "d577eb46d2c3be3d"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 80]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = 24.0
vertical = 65.0
