[meta_properties]
id = "5de9522e184fe962"
asset_kind = "Animation"

[asset_properties]
frame_size = [24, 32]
frame_len = 3
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 12.0
vertical = 22.0
