[meta_properties]
id = "ae10f10a1ccb3dc8"
asset_kind = "Animation"

[asset_properties]
frame_size = [24, 32]
frame_len = 3
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 12.0
vertical = 22.0
