[meta_properties]
id = "cf634c2f59a7d7a3"
asset_kind = "Animation"

[asset_properties]
frame_size = [40, 40]
frame_len = 14
duration = 0.15
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 25.0
