[meta_properties]
id = "1817b607960fd1d"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 48]
frame_len = 4
duration = 0.075
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 30.0
