[meta_properties]
id = "1f855d4e48767042"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 32]
frame_len = 3
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 22.0
