[meta_properties]
id = "88fe2a78f8cc0e37"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 32]
frame_len = 12
duration = [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.8]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 22.0
