[meta_properties]
id = "606ea297bbec35ce"
asset_kind = "Animation"

[asset_properties]
frame_size = [28, 25]
frame_len = 4
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
