[meta_properties]
id = "1977c429e77b20ac"
asset_kind = "Animation"

[asset_properties]
frame_size = [112, 120]
frame_len = 4
duration = 0.25
atlas = "Default"

[asset_properties.offset]
horizontal = 56.0
vertical = 72.0
