[meta_properties]
id = "49f4d4fd0ef34346"
asset_kind = "Animation"

[asset_properties]
frame_size = [40, 32]
frame_len = 4
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 20.0
vertical = 8.0
