[meta_properties]
id = "1d2c3c11343504f5"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 64]
frame_len = 4
duration = [0.2, 1.0, 0.2, 1.4]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 54.0
