[meta_properties]
id = "9eb9b28f133ef64f"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 64]
frame_len = 12
duration = [0.1, 0.25, 0.125, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.175, 1.6]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 54.0
