[meta_properties]
id = "7a225893f81b4d23"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 64]
frame_len = 4
duration = [0.15, 0.15, 0.1, 0.3]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 54.0
