[meta_properties]
id = "b77397e98bb6ac7e"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 4
duration = [0.15, 0.2, 0.15, 0.2]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 32.0
