[meta_properties]
id = "284497b8304f4d70"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 2
duration = [0.125, 0.15]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 54.0
