[meta_properties]
id = "9e51f1487bca4907"
asset_kind = "Animation"

[asset_properties]
frame_size = [64, 64]
frame_len = 4
duration = 0.15
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 46.0
