[meta_properties]
id = "9be6abd7d0d6c2e7"
asset_kind = "Animation"

[asset_properties]
frame_size = [64, 64]
frame_len = 5
duration = [0.075, 0.075, 0.075, 0.075, 0.6]
atlas = "Default"

[asset_properties.offset]
horizontal = 32.0
vertical = 46.0
