[meta_properties]
id = "c999eef67959a4ad"
asset_kind = "Animation"

[asset_properties]
frame_size = [64, 64]
frame_len = 5
duration = [0.075, 0.075, 0.075, 0.075, 0.4]
atlas = "Default"

[asset_properties.offset]
horizontal = 32.0
vertical = 46.0
