[meta_properties]
id = "16623dd8eb5daa05"
asset_kind = "Animation"

[asset_properties]
frame_size = [7, 7]
frame_len = 4
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 3.0
vertical = 3.0
