[meta_properties]
id = "c2316a9cea3ca81f"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 10
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 40.0
vertical = 54.0
