[dying]
kind = "gameplay_triggered"
speaker = "valen"
portrait = "sad"
local = "Ah, you're awake!"
next = "1"

[dying.1]
speaker = "valen"
portrait = "think"
local = "You gave us quite a scare."
next = "2"

[dying.2]
speaker = "valen"
portrait = "mad"
local = "Please take your health more seriously, [Ari]."
next = "3"

[dying.3]
speaker = "valen"
portrait = "think"
local = "You're lucky we found you by that dragon statue in the Mines."
next = "4"

[dying.4]
speaker = "valen"
portrait = "neutral"
local = "Well, I'm glad you seem to be doing better. Let's get you home to rest."
