[meta_properties]
id = "4a7d7b97e726faf4"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 56]
frame_len = 8
duration = 0.125
atlas = "Default"

[asset_properties.offset]
horizontal = 24.0
vertical = 47.0
