[meta_properties]
id = "27313e5d5e70cd62"
asset_kind = "Animation"

[asset_properties]
frame_size = [24, 104]
frame_len = 4
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 8.0
vertical = 88.0
