[meta_properties]
id = "a53bae8c6a7f115"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 7
duration = [0.1, 0.1, 0.5, 0.075, 0.1, 0.075, 0.5]
atlas = "Default"

[asset_properties.offset]
horizontal = 40.0
vertical = 54.0
