[meta_properties]
id = "53566abc6ba90b2c"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 2
duration = 0.05
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 22.0
