[meta_properties]
id = "617d19f78c0cd4fa"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 32]
frame_len = 5
duration = 0.075
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
