[meta_properties]
id = "f1f0c6c77d5ab691"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 3
duration = [0.15, 0.125, 0.125]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 54.0
