[meta_properties]
    id = "86270e05abac839e"
    asset_kind = "MagicEnums"

[asset_properties]

# Any GML Enum with the following name below will
# get generated functions (ie, a magic std function) like:
#
# - `try_enum_snake_case_to_string`, which returns an Option<String>
# - `enum_snake_case_to_string`, which returns a String or throws (and just calls the `try_` variant)
# - `try_string_to_enum_snake_case`, which returns an Option<Enum>
# - `string_to_enum_snake_case`, which returns an Enum or throws (and just calls the `try_` variant)
#
# In all cases above, we both take and return the snake_case version of each enum member name.
# So for exampe, `try_string_to_object_id("worn_table")` will return the number assigned to ObjectId.WornTable.
#
# Additionally, the PascalCase name of the enum is added to the global
# table for format items, so doing `format("{PascalEnumName}", enum_member)` will work.
#
# Enums are expected to be PascalCase, and we will convert function names to be snake_case
# based on https://docs.rs/heck/latest/heck/ conversions.
enum_to_string = [
    "PrizeRarity",
    "ItemId",
    "ObjectId",
    "BarkType",
    "Benchmark",
    "ChildSkinTone",
    "ChildLocation",
    "MonsterCategory",
    "FactoryTier",
    "Status",
    "BugMovementType",
    "BugSpawnType",
    "BugAttraction",
    "CameraTarget",
    "ConditionId",
    "OffSeason",
    "BedKind",
    "TerrainKind",
    "GroundKind",
    "MainExteriorTileIndexes",
    "ObjectCategory",
    "HomeUpgrade",
    "HomeVariant",
    "DungeonImpl",
    "DungeonBiome",
    "DungeonSpawn",
    "GpTriggeredConversation",
    "FishSpawn",
    "FishChestItemKind",
    "FishSize",
    "ForageableRarity",
    "InputType",
    "InputId",
    "BindingType",
    "InputStatus",
    "ItemUse",
    "QualityId",
    "AnimalFeedTier",
    "ToolType",
    "Soulbind",
    "UseItemSuccess",
    "SceneTestTarget",
    "ActivityKind",
    "ActivityState",
    "RoommateState",
    "Desire",
    "NpcId",
    "PathfindErr",
    "PathfindingAgentKind",
    "EndOfDayStatus",
    "RenownEntryType",
    "RewardType",
    "QuestState",
    "QuestCategory",
    "QuestRewardType",
    "QuestQueryType",
    "GatherDropChance",
    "AnimalKind",
    "Sex",
    "FeedKind",
    "BreedingKind",
    "PettingKind",
    "HomeBehavior",
    "AnimalSize",
    "AnimalState",
    "RecipeComponentType",
    "RecipeContext",
    "TileFlag",
    "Warning",
    "T2OutputId",
    "NextLineBehaviorId",
    "T2ActionId",
    "WorldFactId",
    "ConversationKind",
    "Day",
    "Season",
    "DayTimeSpeed",
    "ForecastDescriptor",
    "Weather",
    "MuseumWing",
    "MushroomState",
    "RockclodState",
    "SaplingState",
    "EnchanternState",
    "ElectrocuteKind",
    "MiteState",
    "BatState",
    "MimicState",
    "SpiritState",
    "CatState",
    "RockStackState",
    "BirdAction",
    "Shrine",
    "Daytime",
    "NpcState",
    "StatueState",
    "TomeState",
    "PerpetualSoupStatus",
    "PetKind",
    "PetJob",
    "PetInitialization",
    "PetManagement",
    "PlayerState",
    "FishingEvent",
    "FootstepKind",
    "RangePattern",
    "StatusEffectId",
    "PlayerAnimationEndBehavior",
    "AnimationSlot",
    "AnimationName",
    "Attachment",
    "CurveType",
    "SceneAudioStateId",
    "LoadStateId",
    "ParUiSlot",
    "ShrineMenuVariant",
    "GlyphGuidePriority",
    "InventoryControlMode",
    "InventoryAction",
    "MapHub",
    "ChestIcon",
    "StorageBannerFlag",
    "TextboxState",
    "VitalsElement",
    "NodeId",
    "PilotOverflowBehavior",
    "PilotMovementReturnType",
    "Align",
    "AnchorControl",
    "AnchorLayer",
    "EaseId",
    "Cardinal",
    "Vertical",
    "LogLevel",
    "Activity",
    "Routine",
    "BarkId",
    "Perk",
    "Menu",
    "Skill",
    "LocationId",
    "DungeonDecor",
    "MonsterId",
    "Seal",
    "Infusion",
    "FestivalId",
    "Store",
    "Blueprint",
    "FishId",
    "Tutorial",
    "Bird",
    "RumbleKind",
    "Spell",
    "Light",
    "Date",
    "Requirement",
    "Achievement",
    "ChildId",
    "WorldMod",
    "Pronouns",
    "WaterType",
    "Utero",
    "ChildStage",
    "CameoId",
    "QuestTestTarget",
    "Vsync",
]

# There are enums which are generated based on TOML files.
#
# Each table within the file (or within each file, recursively, when pointed at a folder) in fiddle
# will be the name of an enum.
#
# The enums are sorted alphabetically and they'll have a LEN attribute at the end.
enums_to_generate = [
    { name = "ItemId", path = "items/" },
    { name = "ObjectId", path = "object_prototypes/" },
    { name = "Activity", path = "activities.toml" },
    { name = "Routine", path = "routines.toml" },
    { name = "BarkId", path = "barks.toml" },
    { name = "Perk", path = "perks.toml" },
    { name = "Menu", path = "ui/menus/" },
    { name = "Skill", path = "skills.toml" },
    { name = "LocationId", path = "locations.toml" },
    { name = "DungeonDecor", path = "dungeons/decorations.toml" },
    { name = "MonsterId", path = "monsters/" },
    { name = "Seal", path = "seals.toml" },
    { name = "Infusion", path = "infusions.toml" },
    { name = "FestivalId", path = "festivals.toml" },
    { name = "Store", path = "stores.toml" },
    { name = "Blueprint", path = "blueprints.toml" },
    { name = "FishId", path = "fish.toml" },
    { name = "Tutorial", path = "ui/tutorials.toml" },
    { name = "Bird", path = "birds.toml" },
    { name = "RumbleKind", path = "rumbles.toml" },
    { name = "Spell", path = "spells.toml" },
    { name = "Light", path = "lights.toml" },
    { name = "Date", path = "dates.toml" },
    { name = "Requirement", path = "requirements.toml" },
    { name = "Achievement", path = "achievements.toml" },
    { name = "ChildId", path = "children.toml" },
    { name = "WorldMod", path = "world_mod.toml" },
]
