[meta_properties]
id = "9baa700fa8bfe4df"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 8
duration = 0.075
atlas = "Default"

[asset_properties.offset]
horizontal = 40.0
vertical = 54.0
