[meta_properties]
id = "f2796c842cd153d5"
asset_kind = "Animation"

[asset_properties]
frame_size = [96, 48]
frame_len = 4
duration = 0.15
atlas = "Default"

[asset_properties.offset]
horizontal = 40.0
vertical = 16.0
