[meta_properties]
id = "746d703502f3dcd2"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 48]
frame_len = 5
duration = [0.15, 0.15, 0.15, 0.15, 0.125]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 37.0
