[meta_properties]
id = "8c859aa5d993b79f"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 48]
frame_len = 4
duration = 0.15
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 37.0
