[meta_properties]
id = "bc5855aa17d473c7"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 48]
frame_len = 7
duration = 0.15
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 37.0
