[meta_properties]
id = "a0761fef8c3aee0b"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 9
duration = [0.15, 0.2, 0.3, 0.15, 0.2, 0.3, 0.15, 0.2, 0.3]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 30.0
