[meta_properties]
id = "899bd55653c43d94"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 9
duration = [0.2, 0.1, 0.2, 0.2, 0.1, 0.2, 0.2, 0.1, 0.2]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 30.0
