[meta_properties]
id = "8d7e4c6501b0647b"
asset_kind = "Animation"

[asset_properties]
frame_size = [40, 48]
frame_len = 2
duration = 0.075
atlas = "Default"

[asset_properties.offset]
horizontal = 15.0
vertical = 24.0
