[meta_properties]
id = "21c737f3534e0412"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 48]
frame_len = 16
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 34.0
