[meta_properties]
id = "b19c92dc53748805"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 4
duration = 0.125
atlas = "Default"

[asset_properties.offset]
horizontal = 40.0
vertical = 54.0
