[meta_properties]
id = "3c8d5decd641a272"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 10
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 16.0
