[meta_properties]
id = "88988840b152fcce"
asset_kind = "Animation"

[asset_properties]
frame_size = [64, 64]
frame_len = 2
duration = 0.025
atlas = "Default"

[asset_properties.offset]
horizontal = 34.0
vertical = 36.0
