[meta_properties]
id = "1d29c3daea96d5bc"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 5
duration = [0.125, 0.15, 0.175, 0.125, 0.6]
atlas = "Default"

[asset_properties.offset]
horizontal = 40.0
vertical = 54.0
