[meta_properties]
id = "917f6d9da3020147"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 32]
frame_len = 4
duration = [0.2, 1.2, 0.2, 0.8]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 22.0
