[meta_properties]
id = "40109d25869e5044"
asset_kind = "Animation"

[asset_properties]
frame_size = [40, 40]
frame_len = 13
duration = 0.15
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 25.0
