[meta_properties]
id = "82d77b89ced3e429"
asset_kind = "Animation"

[asset_properties]
frame_size = [64, 56]
frame_len = 5
duration = [0.125, 0.1, 0.1, 0.1, 0.125]
atlas = "Default"

[asset_properties.offset]
horizontal = 32.0
vertical = 40.0
