[meta_properties]
id = "5187d926fd97b288"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 32]
frame_len = 34
duration = [0.8, 1.0, 0.75, 0.65, 0.85, 0.2, 0.8, 0.2, 1.2, 0.2, 0.8, 0.2, 1.2, 0.8, 0.1, 0.1, 0.1, 0.8, 1.0, 0.75, 0.65, 0.85, 0.2, 0.8, 0.2, 1.2, 0.2, 0.8, 0.2, 1.2, 0.8, 0.1, 0.1, 0.1]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 22.0
