[meta_properties]
id = "64ce49a022c0105d"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 56]
frame_len = 8
duration = 0.125
atlas = "Default"

[asset_properties.offset]
horizontal = 24.0
vertical = 48.0
