[meta_properties]
id = "7adf2341847f905e"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 56]
frame_len = 4
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 24.0
vertical = 48.0
