[meta_properties]
id = "b3ddd2ed515a88f5"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 6
duration = [0.15, 0.15, 0.45, 0.1, 0.075, 1.0]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 54.0
