[meta_properties]
id = "80d7bdb0a767070c"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 4
duration = [0.2, 1.0, 0.2, 1.4]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 30.0
