[meta_properties]
id = "efcc881103e4849a"
asset_kind = "Animation"

[asset_properties]
frame_size = [56, 56]
frame_len = 21
duration = [0.15, 0.15, 0.15, 0.15, 0.25, 0.15, 0.15, 0.15, 0.25, 0.15, 0.15, 0.15, 0.15, 0.25, 0.15, 0.15, 0.15, 0.25, 0.15, 0.15, 0.15]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 46.0
