[meta_properties]
id = "2932c83c5402f65f"
asset_kind = "Animation"

[asset_properties]
frame_size = [56, 56]
frame_len = 3
duration = [0.05, 0.15, 0.05]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 46.0
