[meta_properties]
id = "e87be23f1f0345ba"
asset_kind = "Animation"

[asset_properties]
frame_size = [56, 56]
frame_len = 9
duration = [0.4, 0.1, 0.15, 0.1, 0.1, 0.1, 0.1, 0.1, 1.7]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 46.0
