[meta_properties]
id = "a3d93e6c53df32fc"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 4
duration = 0.15
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 30.0
