[meta_properties]
id = "30f9d217b5536c4b"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 15
duration = [0.1, 0.1, 0.1, 0.1, 0.1, 0.2, 0.1, 0.1, 0.1, 0.1, 0.1, 0.4, 0.1, 0.1, 0.8]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 54.0
