[meta_properties]
id = "bdea39aff6c9b72"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 2
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = 40.0
vertical = 54.0
