[meta_properties]
id = "ccc3c62edb18971e"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 6
duration = [0.125, 1.6, 0.125, 1.6, 0.125, 1.6]
atlas = "Default"

[asset_properties.offset]
horizontal = 40.0
vertical = 54.0
