[meta_properties]
id = "1fd3ed47d975a75c"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 2
duration = [0.15, 0.125]
atlas = "Default"

[asset_properties.offset]
horizontal = 40.0
vertical = 54.0
