[meta_properties]
id = "d1712820a895e5e4"
asset_kind = "Animation"

[asset_properties]
frame_size = [200, 104]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = 96.0
vertical = 23.0
