[meta_properties]
id = "b7af05d8c5f8c77"
asset_kind = "Animation"

[asset_properties]
frame_size = [24, 40]
frame_len = 3
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 12.0
vertical = 30.0
