[meta_properties]
id = "be6ae89b5235d02b"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 64]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = 8.0
vertical = 52.0
