[meta_properties]
id = "852f668b426d8b39"
asset_kind = "Animation"

[asset_properties]
frame_size = [16, 32]
frame_len = 6
duration = [0.1, 0.1, 0.25, 0.1, 0.1, 0.2]
atlas = "Default"

[asset_properties.offset]
horizontal = 8.0
vertical = 8.0
