[meta_properties]
id = "cb94c4f7aa9e7a0e"
asset_kind = "Animation"

[asset_properties]
frame_size = [13, 8]
frame_len = 7
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
