[meta_properties]
id = "aa40021257ac0001"
asset_kind = "Animation"

[asset_properties]
frame_size = [64, 64]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = 32.0
vertical = 63.0
