[meta_properties]
id = "f13fbe0e9fe8bbfe"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 32]
frame_len = 8
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 24.0
