[meta_properties]
id = "244259cad56315d6"
asset_kind = "Animation"

[asset_properties]
frame_size = [144, 88]
frame_len = 6
duration = [0.4, 0.2, 0.2, 0.4, 0.2, 0.2]
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 26.0
