[meta_properties]
id = "f27c676c4fdc7253"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 5
duration = [0.1, 0.1, 0.075, 0.1, 0.8]
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 30.0
