[meta_properties]
id = "a84922b9291672c3"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 4
duration = [0.2, 0.8, 0.2, 1.2]
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 30.0
