[meta_properties]
id = "dcf0223e43c954a9"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 4
duration = 0.15
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 30.0
