[meta_properties]
id = "b57ce661238df616"
asset_kind = "Animation"

[asset_properties]
frame_size = [120, 136]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = 56.0
vertical = 120.0
