[meta_properties]
id = "292fee296ee8eb4c"
asset_kind = "Animation"

[asset_properties]
frame_size = [152, 40]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = 76.0
vertical = 8.0
