[meta_properties]
id = "2289fa9a723dc5a0"
asset_kind = "Animation"

[asset_properties]
frame_size = [56, 56]
frame_len = 10
duration = [0.15, 1.4, 0.15, 0.15, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3]
atlas = "Default"

[asset_properties.offset]
horizontal = 28.0
vertical = 46.0
