[meta_properties]
id = "22c3abcdadf10bc9"
asset_kind = "Animation"

[asset_properties]
frame_size = [56, 56]
frame_len = 4
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 28.0
vertical = 46.0
