[meta_properties]
id = "982a1bf95bfc0d7b"
asset_kind = "Animation"

[asset_properties]
frame_size = [56, 56]
frame_len = 8
duration = 0.125
atlas = "Default"

[asset_properties.offset]
horizontal = 28.0
vertical = 46.0
