[meta_properties]
id = "3c84c4a38586657e"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = 8.0
vertical = 21.0
