[meta_properties]
id = "c5cdb9c7e9b41af"
asset_kind = "Animation"

[asset_properties]
frame_size = [40, 48]
frame_len = 2
duration = 0.075
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 28.0
