[meta_properties]
id = "b5de128d43b40b74"
asset_kind = "Animation"

[asset_properties]
frame_size = [72, 80]
frame_len = 3
duration = [0.2, 0.1, 0.4]
atlas = "Default"

[asset_properties.offset]
horizontal = 36.0
vertical = 52.0
