[meta_properties]
id = "ae531783f6f3d0b2"
asset_kind = "Animation"

[asset_properties]
frame_size = [72, 80]
frame_len = 8
duration = 0.05
atlas = "Default"

[asset_properties.offset]
horizontal = 36.0
vertical = 52.0
