[meta_properties]
id = "8f20119503e57514"
asset_kind = "Animation"

[asset_properties]
frame_size = [72, 80]
frame_len = 7
duration = [0.05, 0.05, 0.05, 0.05, 0.075, 0.075, 0.15]
atlas = "Default"

[asset_properties.offset]
horizontal = 36.0
vertical = 52.0
