[meta_properties]
id = "eb5465f987de900b"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 40]
frame_len = 4
duration = 0.15
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 31.0
