[meta_properties]
id = "3cdeaace466f8544"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 56]
frame_len = 3
duration = [0.05, 0.15, 0.05]
atlas = "Default"

[asset_properties.offset]
horizontal = 24.0
vertical = 48.0
