[meta_properties]
id = "aa4c1aa6afc21f7d"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 3
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 54.0
