[meta_properties]
id = "ac367f7789670d79"
asset_kind = "Animation"

[asset_properties]
frame_size = [11, 11]
frame_len = 9
duration = 0.1
atlas = "UI"

[asset_properties.offset]
horizontal = 5.0
vertical = 5.0
