[meta_properties]
id = "127d3f448487d715"
asset_kind = "Animation"

[asset_properties]
frame_size = [16, 32]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = 8.0
vertical = 27.0
