[meta_properties]
id = "16fe6bdc04a0a865"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 56]
frame_len = 2
duration = 0.075
atlas = "Default"

[asset_properties.offset]
horizontal = 12.0
vertical = 45.0
