[meta_properties]
id = "16b708cbb335d8f9"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 24
duration = [0.1, 0.15, 0.2, 0.15, 0.1, 0.1, 0.15, 0.2, 0.15, 0.1, 0.1, 0.5, 0.1, 0.5, 0.1, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.1]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 31.0
