[meta_properties]
id = "d3f71eddacc96b8b"
asset_kind = "Animation"

[asset_properties]
frame_size = [24, 24]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
