[meta_properties]
id = "70f8158df4e2bfe7"
asset_kind = "Animation"

[asset_properties]
frame_size = [15, 9]
frame_len = 4
duration = 0.075
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
