[meta_properties]
id = "79a8fad25b378f38"
asset_kind = "Animation"

[asset_properties]
frame_size = [24, 24]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = 12.0
vertical = 14.0
