[meta_properties]
id = "cf6250f2bdb057b"
asset_kind = "Animation"

[asset_properties]
frame_size = [24, 24]
frame_len = 2
duration = 0.5
atlas = "Default"

[asset_properties.offset]
horizontal = 12.0
vertical = 14.0
