[meta_properties]
id = "c39944006d3f40c5"
asset_kind = "Animation"

[asset_properties]
frame_size = [40, 32]
frame_len = 4
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 22.0
