[meta_properties]
id = "f6673cc8d3f2b13b"
asset_kind = "Animation"

[asset_properties]
frame_size = [40, 32]
frame_len = 4
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 22.0
