[meta_properties]
id = "6b203b2b8c0d6b97"
asset_kind = "Animation"

[asset_properties]
frame_size = [56, 56]
frame_len = 5
duration = [0.1, 0.1, 0.1, 0.1, 0.25]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 46.0
