[meta_properties]
id = "20f9c64a620b2d8f"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 2
duration = [0.125, 0.1]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 54.0
