[meta_properties]
id = "1d0ccbef78311b21"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 2
duration = [0.25, 0.175]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 54.0
