[meta_properties]
id = "8e20279a347aaafa"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 32]
frame_len = 4
duration = [1.0, 0.75, 0.65, 0.85]
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 22.0
