[meta_properties]
id = "7bb56f57dc28bb80"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 56]
frame_len = 8
duration = [0.15, 0.2, 0.15, 0.2, 0.15, 0.2, 0.15, 0.2]
atlas = "Default"

[asset_properties.offset]
horizontal = 24.0
vertical = 48.0
