[meta_properties]
id = "b2a49a32c3494f68"
asset_kind = "Animation"

[asset_properties]
frame_size = [56, 56]
frame_len = 4
duration = 0.125
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 46.0
