[meta_properties]
id = "c463ab4292110618"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = 8.0
vertical = 16.0
