[meta_properties]
id = "4dbab568d41c55dc"
asset_kind = "Animation"

[asset_properties]
frame_size = [8, 16]
frame_len = 4
duration = 0.125
atlas = "Default"

[asset_properties.offset]
horizontal = 4.0
vertical = 12.0
