[meta_properties]
id = "76e5d0afddda56b3"
asset_kind = "Animation"

[asset_properties]
frame_size = [56, 56]
frame_len = 4
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 46.0
