[meta_properties]
id = "c6e40f53ec0eb9e2"
asset_kind = "Animation"

[asset_properties]
frame_size = [56, 56]
frame_len = 9
duration = [0.4, 0.1, 0.15, 0.1, 0.1, 0.1, 0.1, 0.1, 1.7]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 46.0
