[meta_properties]
id = "db82845f3a169dc5"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 8
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 40.0
vertical = 54.0
