[meta_properties]
id = "7885f3245fa1d7fa"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 40]
frame_len = 8
duration = [0.8, 0.05, 0.15, 0.05, 0.125, 0.125, 0.125, 1.2]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 31.0
