[meta_properties]
id = "f5071ae73ad26918"
asset_kind = "Animation"

[asset_properties]
frame_size = [40, 40]
frame_len = 3
duration = [0.1, 0.15, 0.1]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 25.0
