[meta_properties]
id = "4cd41044cd164fce"
asset_kind = "Animation"

[asset_properties]
frame_size = [40, 40]
frame_len = 8
duration = [0.1, 0.2, 0.1, 0.2, 0.1, 0.2, 0.1, 0.2]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 25.0
