[meta_properties]
id = "2312f3eee9b17636"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 10
duration = 0.075
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 32.0
