[meta_properties]
id = "67bca6d760209bef"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 8
duration = 0.125
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 32.0
