[meta_properties]
id = "b946e97d055eb6a2"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 5
duration = [0.1, 0.075, 0.05, 0.05, 0.05]
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 32.0
