[meta_properties]
id = "3c39a3ee84038169"
asset_kind = "Animation"

[asset_properties]
frame_size = [16, 24]
frame_len = 4
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 8.0
vertical = 20.0
