[meta_properties]
id = "c1eb419c8c52af8d"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 32]
frame_len = 9
duration = [0.1, 0.1, 0.2, 0.1, 0.2, 0.1, 0.6, 0.1, 0.1]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 22.0
