[meta_properties]
id = "c4eb93958c03c6ff"
asset_kind = "Animation"

[asset_properties]
frame_size = [16, 32]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = 8.0
vertical = 24.0
