[meta_properties]
id = "d27804d03f87b30b"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 5
duration = [0.5, 0.1, 0.5, 0.1, 0.8]
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 30.0
