[meta_properties]
id = "6e060eaf79608f8f"
asset_kind = "Animation"

[asset_properties]
frame_size = [40, 32]
frame_len = 4
duration = [0.2, 1.2, 0.2, 0.8]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 22.0
