[meta_properties]
id = "24e1fd8fc3f0d42d"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 40]
frame_len = 3
duration = 0.075
atlas = "Default"

[asset_properties.offset]
horizontal = 24.0
vertical = 24.0
