[meta_properties]
id = "ddfe40759c6a8a2f"
asset_kind = "Animation"

[asset_properties]
frame_size = [64, 64]
frame_len = 4
duration = [0.075, 0.075, 0.075, 0.5]
atlas = "Default"

[asset_properties.offset]
horizontal = 32.0
vertical = 46.0
