[meta_properties]
id = "b4b6f4d01b5d0afd"
asset_kind = "Animation"

[asset_properties]
frame_size = [64, 64]
frame_len = 5
duration = [0.075, 0.075, 0.075, 0.075, 0.6]
atlas = "Default"

[asset_properties.offset]
horizontal = 32.0
vertical = 46.0
