[meta_properties]
id = "1b1b485d6c1921b7"
asset_kind = "Animation"

[asset_properties]
frame_size = [64, 64]
frame_len = 7
duration = [0.05, 0.05, 0.05, 0.05, 0.075, 0.075, 0.15]
atlas = "Default"

[asset_properties.offset]
horizontal = 32.0
vertical = 46.0
