[meta_properties]
id = "522d3dd9240067a"
asset_kind = "Animation"

[asset_properties]
frame_size = [64, 64]
frame_len = 8
duration = [0.1, 0.075, 0.075, 0.1, 0.1, 0.1, 0.1, 0.1]
atlas = "Default"

[asset_properties.offset]
horizontal = 32.0
vertical = 46.0
