[meta_properties]
id = "ebfb07296d48a07f"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 32]
frame_len = 8
duration = 0.075
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 16.0
