[meta_properties]
id = "e744ad425c6d784"
asset_kind = "Animation"

[asset_properties]
frame_size = [160, 112]
frame_len = 20
duration = [0.4, 0.1, 0.15, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.2, 0.4, 0.1, 0.15, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.2]
atlas = "Default"

[asset_properties.offset]
horizontal = 80.0
vertical = 60.0
