[meta_properties]
id = "972b6a53514b1740"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 24.0
