[meta_properties]
id = "f203f65adc6c9af2"
asset_kind = "Animation"

[asset_properties]
frame_size = [96, 80]
frame_len = 24
duration = 0.15
atlas = "Default"

[asset_properties.offset]
horizontal = 52.0
vertical = 25.0
