[meta_properties]
id = "73c8f6f2c5dd3ee5"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 56]
frame_len = 4
duration = 0.125
atlas = "Default"

[asset_properties.offset]
horizontal = 24.0
vertical = 48.0
