[meta_properties]
id = "9c3f65101c063a70"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 2
duration = 0.125
atlas = "Default"

[asset_properties.offset]
horizontal = 40.0
vertical = 54.0
