[meta_properties]
id = "ba1a6eba4c70fcee"
asset_kind = "Animation"

[asset_properties]
frame_size = [9, 9]
frame_len = 7
duration = 0.075
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
