[meta_properties]
id = "cbfd9eadf6e9f1a6"
asset_kind = "Animation"

[asset_properties]
frame_size = [20, 20]
frame_len = 4
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 10.0
vertical = 10.0
