[meta_properties]
id = "2d5e95ea752a382b"
asset_kind = "Animation"

[asset_properties]
frame_size = [65, 65]
frame_len = 8
duration = 0.05
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
