[meta_properties]
id = "fb789297c2099151"
asset_kind = "Animation"

[asset_properties]
frame_size = [20, 20]
frame_len = 13
duration = [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.8]
atlas = "Default"

[asset_properties.offset]
horizontal = 10.0
vertical = 10.0
