[meta_properties]
id = "d588b98a23f088bc"
asset_kind = "Animation"

[asset_properties]
frame_size = [14, 13]
frame_len = 4
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = "Left"
vertical = 9.0
