[meta_properties]
id = "6eb75e17ec731355"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 32]
frame_len = 4
duration = 0.125
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 25.0
