[meta_properties]
id = "7b9a1a19816e655c"
asset_kind = "Animation"

[asset_properties]
frame_size = [56, 56]
frame_len = 9
duration = [0.15, 0.2, 0.3, 0.15, 0.2, 0.3, 0.15, 0.2, 0.3]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 42.0
