[meta_properties]
id = "2bda508b5d44b6e1"
asset_kind = "Animation"

[asset_properties]
frame_size = [16, 16]
frame_len = 21
duration = [0.1, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
atlas = "UI"
