[meta_properties]
id = "9cf62ec5d01c287b"
asset_kind = "Animation"

[asset_properties]
frame_size = [64, 72]
frame_len = 6
duration = 0.08
atlas = "Default"

[asset_properties.offset]
horizontal = 32.0
vertical = 58.0
