[meta_properties]
id = "ae98427398bc7fce"
asset_kind = "Animation"

[asset_properties]
frame_size = [64, 48]
frame_len = 4
duration = 0.15
atlas = "Default"

[asset_properties.offset]
horizontal = 32.0
vertical = 24.0
