[meta_properties]
id = "1b0c7da515dc132a"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 4
duration = [0.1, 0.075, 0.1, 0.075]
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 30.0
