[meta_properties]
id = "f1bbb21974e25aec"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 2
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 30.0
