[meta_properties]
id = "dd51e5b48f0fb64b"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 4
duration = 0.075
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 30.0
