[meta_properties]
id = "d189c383a6f765d1"
asset_kind = "Animation"

[asset_properties]
frame_size = [16, 32]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = "Left"
vertical = 16.0
