[meta_properties]
id = "16807dc74d926165"
asset_kind = "Animation"

[asset_properties]
frame_size = [64, 80]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = 32.0
vertical = 72.0
