[meta_properties]
id = "348c0fa753c2226f"
asset_kind = "Animation"

[asset_properties]
frame_size = [152, 152]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
