[meta_properties]
id = "5c70e420ca901e5b"
asset_kind = "Animation"

[asset_properties]
frame_size = [120, 120]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
