[meta_properties]
id = "6f52c31c47581a72"
asset_kind = "Animation"

[asset_properties]
frame_size = [24, 24]
frame_len = 4
duration = 0.15
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
