[meta_properties]
id = "e2990ffc70caeff6"
asset_kind = "Animation"

[asset_properties]
frame_size = [96, 96]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
