[meta_properties]
id = "6818e7affe980794"
asset_kind = "Animation"

[asset_properties]
frame_size = [104, 104]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
