[meta_properties]
id = "7ee2d812abe87da5"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 64]
frame_len = 4
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 40.0
vertical = 55.0
