[meta_properties]
id = "9dc9c696230df8ea"
asset_kind = "Animation"

[asset_properties]
frame_size = [46, 38]
frame_len = 4
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 20.0
vertical = 19.0
