[meta_properties]
id = "378819ab9dc51e9"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 48]
frame_len = 14
duration = [0.15, 0.15, 0.15, 0.15, 0.15, 0.3, 0.3, 0.15, 0.15, 0.15, 0.15, 0.15, 0.3, 0.15]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 29.0
