[meta_properties]
id = "aa7298ce62dae5cc"
asset_kind = "Animation"

[asset_properties]
frame_size = [40, 40]
frame_len = 4
duration = [1.2, 0.2, 0.8, 0.2]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 25.0
