[meta_properties]
id = "342b4343757f4455"
asset_kind = "Animation"

[asset_properties]
frame_size = [40, 40]
frame_len = 14
duration = 0.15
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 25.0
