[meta_properties]
id = "a4b5e8569cec39ad"
asset_kind = "Animation"

[asset_properties]
frame_size = [40, 40]
frame_len = 4
duration = 0.125
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 25.0
