[meta_properties]
id = "9d52cb35d88aec3b"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 32]
frame_len = 4
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 22.0
