[meta_properties]
id = "86293e5ef5b1ed44"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 32]
frame_len = 2
duration = 0.025
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 22.0
