[meta_properties]
id = "d2701c078c75ab2b"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 48]
frame_len = 4
duration = 0.05
atlas = "Default"

[asset_properties.offset]
horizontal = 24.0
vertical = 26.0
