[meta_properties]
id = "60c0b2d4e1910e18"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 32]
frame_len = 2
duration = 0.025
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 22.0
