[meta_properties]
id = "a415ae5f1ff1b19e"
asset_kind = "Animation"

[asset_properties]
frame_size = [6, 7]
frame_len = 16
duration = 0.05
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
