[meta_properties]
id = "5ad21111806952fd"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 4
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 54.0
