[meta_properties]
id = "1aaa2e7647ca768c"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 4
duration = 0.125
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 54.0
