[meta_properties]
id = "381d2641a89d4f75"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 32]
frame_len = 6
duration = [0.15, 0.15, 0.15, 0.4, 0.15, 0.1]
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 22.0
