[meta_properties]
id = "d2bf9230cd50cc0b"
asset_kind = "Animation"

[asset_properties]
frame_size = [16, 40]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = 8.0
vertical = 27.0
