[meta_properties]
id = "81649b622a135145"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 3
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 24.0
