[meta_properties]
id = "d83a6c124f07fd37"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 4
duration = 0.15
atlas = "Default"

[asset_properties.offset]
horizontal = 40.0
vertical = 54.0
