[meta_properties]
id = "7637fd9a5cf11e1f"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 32]
frame_len = 4
duration = [0.075, 0.075, 0.1, 0.5]
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 22.0
