[meta_properties]
id = "87b477c08c15de7d"
asset_kind = "Animation"

[asset_properties]
frame_size = [24, 32]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = 8.0
vertical = 24.0
