[meta_properties]
id = "1168ce3995ffce4d"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 32]
frame_len = 6
duration = [0.075, 0.075, 0.075, 0.1, 0.1, 0.4]
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 16.0
