[meta_properties]
id = "aa2c6f572ce2b5de"
asset_kind = "Animation"

[asset_properties]
frame_size = [25, 20]
frame_len = 6
duration = [0.075, 0.075, 0.075, 0.075, 0.075, 0.8]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 12.0
