[meta_properties]
id = "e4a4ac8792752314"
asset_kind = "Animation"

[asset_properties]
frame_size = [17, 22]
frame_len = 6
duration = [0.075, 0.075, 0.075, 0.075, 0.075, 0.8]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 13.0
