[meta_properties]
id = "29d7c06632653d27"
asset_kind = "Animation"

[asset_properties]
frame_size = [18, 18]
frame_len = 17
duration = [0.1, 0.1, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.1, 0.1, 0.1, 0.4]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
