[meta_properties]
id = "cad806d2ada9d99f"
asset_kind = "Animation"

[asset_properties]
frame_size = [52, 52]
frame_len = 8
duration = 0.075
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
