[meta_properties]
id = "61f5707328895b63"
asset_kind = "Animation"

[asset_properties]
frame_size = [23, 20]
frame_len = 6
duration = [0.075, 0.075, 0.075, 0.075, 0.075, 0.8]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 12.0
