[meta_properties]
id = "cf2a9257f2730ffc"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 2
duration = [0.225, 0.325]
atlas = "Default"

[asset_properties.offset]
horizontal = 40.0
vertical = 54.0
