[meta_properties]
id = "c97c78e9e4c60d1b"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 2
duration = [0.225, 0.325]
atlas = "Default"

[asset_properties.offset]
horizontal = 40.0
vertical = 54.0
