[meta_properties]
id = "affb257d4ea1f795"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 32]
frame_len = 4
duration = 0.325
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 22.0
