[meta_properties]
id = "f62114eedcb1f798"
asset_kind = "Animation"

[asset_properties]
frame_size = [9, 12]
frame_len = 2
duration = 0.15
atlas = "Default"

[asset_properties.offset]
horizontal = 4.0
vertical = 8.0
