[meta_properties]
id = "af561d52d7dd8a9b"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 48]
frame_len = 4
duration = [0.2, 0.8, 0.2, 1.2]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 30.0
