[meta_properties]
id = "b987432b87b990a9"
asset_kind = "Animation"

[asset_properties]
frame_size = [16, 16]
frame_len = 4
duration = 0.05
atlas = "Default"

[asset_properties.offset]
horizontal = 8.0
vertical = 12.0
