[meta_properties]
id = "f73e480228a7398c"
asset_kind = "Animation"

[asset_properties]
frame_size = [16, 16]
frame_len = 4
duration = 0.05
atlas = "Default"

[asset_properties.offset]
horizontal = 8.0
vertical = 12.0
