[meta_properties]
id = "d5414947d0d20b0e"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 32]
frame_len = 13
duration = [0.15, 0.15, 0.15, 0.15, 0.15, 0.3, 0.3, 0.15, 0.15, 0.15, 0.15, 0.15, 0.3]
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 21.0
