[meta_properties]
id = "249f84a08be02b1d"
asset_kind = "Animation"

[asset_properties]
frame_size = [16, 56]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = 8.0
vertical = 55.0
