[meta_properties]
id = "6db4fc2bf8558b3a"
asset_kind = "Shape"
required_assets = ["faf2dc15dd8bbc02", "d32223b9f20171b9", "fac8f5ad7f76c804", "930e2b17a3b6b53a"]

[asset_properties]
kind = "box"
offset = [-5, -17]
dimensions = [10, 21]
