[meta_properties]
id = "6faf8f2cdd0b0e12"
asset_kind = "Shape"
required_assets = ["28df557a5404afdf", "8efce56a5bfb9748", "4cb709504edc049f"]

[asset_properties]
kind = "box"
offset = [-15, 0]
dimensions = [30, 30]
