[meta_properties]
id = "3381a9ebedba3886"
asset_kind = "Shape"
required_assets = ["fa1ebede8fa23899", "68108d87a0340f97", "69cdd81c8053be1", "c93ee4dbf3b152af"]

[asset_properties]
kind = "box"
offset = [-14, -18]
dimensions = [28, 26]
