[meta_properties]
id = "de7787c73e6c9788"
asset_kind = "Shape"
required_assets = ["98dda5d6ae2d7b1", "6ee2d99a8dccf22", "fc8a2208103f63"]

[asset_properties]
kind = "box"
offset = [-73, -191]
dimensions = [146, 204]
