[meta_properties]
id = "d861c3e2b5c6109"
asset_kind = "Shape"
required_assets = ["2ec57e3c22aee2a9", "bd91641c3dbb833", "6236afae0276bbc", "fc1de6f63b25458f", "2aba4c8fb0d3886d"]

[asset_properties]
kind = "box"
offset = [-68, -172]
dimensions = [136, 184]
