[meta_properties]
id = "98dd18ba0663686a"
asset_kind = "Shape"
required_assets = ["23e080e27bee0e6a", "6fed25f51f32cb00", "a75abcdab71e24ec", "2909f18be6aa129f"]

[asset_properties]
kind = "box"
offset = [-5, -12]
dimensions = [10, 16]
