[meta_properties]
id = "d1d5d037fe989cfa"
asset_kind = "Shape"
required_assets = ["3afe3100de0d5596", "4dbe39a600e91fef", "339545f4ba32003b", "2921017790af3e79"]

[asset_properties]
kind = "box"
offset = [-4, -9]
dimensions = [8, 13]
