[meta_properties]
id = "ff266244a9fc700"
asset_kind = "Shape"
required_assets = ["53bccb8e82206b7b", "cfe43a8fa6f4b2f9", "53f7a5d10a2d4eb8"]

[asset_properties]
kind = "box"
offset = [-73, -191]
dimensions = [146, 204]
