[meta_properties]
id = "977a0615deab9578"
asset_kind = "Shape"
required_assets = ["1d73a585ac30491d", "1717a175fcb7524a", "38ff6686e25b465c"]

[asset_properties]
kind = "box"
offset = [-12, -51]
dimensions = [24, 48]
