[meta_properties]
id = "15bf87b5977d5f78"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 64]
frame_len = 8
duration = 0.15
atlas = "Default"

[asset_properties.offset]
horizontal = 24.0
vertical = 48.0
