[meta_properties]
id = "92ab61041a6d1a68"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 40]
frame_len = 15
duration = [0.15, 0.15, 0.3, 0.4, 0.3, 0.25, 0.15, 0.15, 0.3, 0.25, 0.15, 0.3, 0.25, 0.15, 0.3]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 31.0
