[meta_properties]
id = "1b328f1a715744c"
asset_kind = "Animation"

[asset_properties]
frame_size = [16, 40]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = 8.0
vertical = 39.0
