[meta_properties]
id = "c3094cbcc6e9b8c6"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 7
duration = [0.1, 0.25, 0.25, 0.25, 0.25, 0.1, 0.4]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 54.0
