[meta_properties]
id = "f4ddf26866947ae2"
asset_kind = "Animation"

[asset_properties]
frame_size = [56, 71]
frame_len = 3
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 28.0
vertical = 52.0
