[meta_properties]
id = "da1fc1e2f875909f"
asset_kind = "Animation"

[asset_properties]
frame_size = [296, 180]
frame_len = 7
duration = [0.075, 0.075, 0.075, 0.1, 0.075, 0.075, 0.5]
atlas = "PortraitsMisc"
