[meta_properties]
id = "e343ad3aee7323ec"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 4
duration = [0.325, 0.125, 0.3, 0.125]
atlas = "Default"

[asset_properties.offset]
horizontal = 40.0
vertical = 54.0
