[meta_properties]
id = "68db725288ba45ad"
asset_kind = "Animation"

[asset_properties]
frame_size = [56, 48]
frame_len = 2
duration = 0.075
atlas = "Default"

[asset_properties.offset]
horizontal = 24.0
vertical = 24.0
