[meta_properties]
id = "83bf4f3533be0f7a"
asset_kind = "Animation"

[asset_properties]
frame_size = [72, 88]
frame_len = 8
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 32.0
vertical = 64.0
