[meta_properties]
id = "1d0cfbdb264e4879"
asset_kind = "Animation"

[asset_properties]
frame_size = [40, 48]
frame_len = 72
duration = 0.075
atlas = "Default"

[asset_properties.offset]
horizontal = 20.0
vertical = 32.0
