[meta_properties]
id = "f931f6fd8d40f4fd"
asset_kind = "Animation"

[asset_properties]
frame_size = [36, 64]
frame_len = 6
duration = 0.025
atlas = "Default"

[asset_properties.offset]
horizontal = 20.0
vertical = 36.0
