[meta_properties]
id = "c01d2e9248533feb"
asset_kind = "Animation"

[asset_properties]
frame_size = [40, 32]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 22.0
