[meta_properties]
id = "f882e52b350d7cf6"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 48]
frame_len = 4
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 24.0
vertical = 32.0
