[meta_properties]
id = "cea97297eac18b59"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 6
duration = [0.1, 0.5, 0.1, 0.5, 0.1, 0.8]
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 30.0
