[meta_properties]
id = "de5f3a431f29560d"
asset_kind = "Animation"

[asset_properties]
frame_size = [40, 48]
frame_len = 4
duration = [0.1, 0.1, 0.1, 0.5]
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 28.0
