[meta_properties]
id = "46303e8824bb1a05"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 2
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 12.0
vertical = 19.0
