[meta_properties]
id = "760de04ddd5a5d6f"
asset_kind = "Animation"

[asset_properties]
frame_size = [56, 56]
frame_len = 4
duration = [0.15, 0.15, 0.1, 0.3]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 42.0
