[meta_properties]
id = "ad51d1a894fb1413"
asset_kind = "Animation"

[asset_properties]
frame_size = [56, 56]
frame_len = 12
duration = [0.1, 0.1, 0.1, 0.2, 0.1, 0.1, 0.1, 0.2, 0.1, 0.1, 0.1, 0.2]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 42.0
