[meta_properties]
id = "4566c0b57694f059"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 48]
frame_len = 4
duration = 0.15
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 26.0
