[meta_properties]
id = "2ee6705a3848e1a4"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 9
duration = [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.1]
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 24.0
