[meta_properties]
id = "db59eb4345271c8d"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 32]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 16.0
