[meta_properties]
id = "dcf0945bd2c2dd22"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 7
duration = [0.5, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 54.0
