[meta_properties]
id = "cbb1b6f1db78279b"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 3
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 40.0
vertical = 54.0
