[meta_properties]
id = "149ac3289ce27a51"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 3
duration = [0.1, 0.15, 1.0]
atlas = "Default"

[asset_properties.offset]
horizontal = 40.0
vertical = 54.0
