[meta_properties]
id = "6059c9c45c513e86"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 8
duration = [0.1, 0.4, 0.1, 0.6, 0.1, 0.4, 0.1, 0.6]
atlas = "Default"

[asset_properties.offset]
horizontal = 40.0
vertical = 54.0
