[meta_properties]
id = "63c12b00b73d5f51"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 3
duration = 0.125
atlas = "Default"

[asset_properties.offset]
horizontal = 40.0
vertical = 54.0
