[meta_properties]
id = "127381804e7a4d64"
asset_kind = "Animation"

[asset_properties]
frame_size = [40, 32]
frame_len = 14
duration = [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.8]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 22.0
