[meta_properties]
id = "ec4ae0759f8633e7"
asset_kind = "Animation"

[asset_properties]
frame_size = [40, 56]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = 19.0
vertical = 47.0
