[meta_properties]
id = "daf746e30b617da9"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 56]
frame_len = 7
duration = 0.075
atlas = "Default"

[asset_properties.offset]
horizontal = 24.0
vertical = 48.0
