[meta_properties]
id = "16f61a5f054f02e2"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 48]
frame_len = 12
duration = [0.075, 0.075, 0.075, 0.075, 0.075, 0.075, 0.075, 0.075, 0.075, 0.075, 0.075, 0.15]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Bottom"
