[meta_properties]
id = "6fccab8f0776aefb"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 56]
frame_len = 11
duration = 0.075
atlas = "Default"

[asset_properties.offset]
horizontal = 24.0
vertical = 48.0
