[meta_properties]
id = "250d8308d53b0ded"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 64]
frame_len = 6
duration = 0.125
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 55.0
