[meta_properties]
id = "2e25e69460e0e36a"
asset_kind = "Animation"

[asset_properties]
frame_size = [80, 80]
frame_len = 4
duration = 0.125
atlas = "Default"

[asset_properties.offset]
horizontal = 40.0
vertical = 54.0
