[meta_properties]
id = "cba133dde8cf5626"
asset_kind = "Animation"

[asset_properties]
frame_size = [184, 112]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = 88.0
vertical = 80.0
