[meta_properties]
id = "f91c68cbc4a385ac"
asset_kind = "Animation"

[asset_properties]
frame_size = [184, 112]
frame_len = 4
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = 88.0
vertical = 23.0
