[meta_properties]
id = "ba6b5d45fe5d1617"
asset_kind = "Animation"

[asset_properties]
frame_size = [6, 7]
frame_len = 16
duration = 0.05
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = "Middle"
