[meta_properties]
id = "2085cf4e9c03338"
asset_kind = "Animation"

[asset_properties]
frame_size = [67, 51]
frame_len = 2
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = "Left"
vertical = 22.0
