[meta_properties]
id = "a395b14e4184f40b"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 56]
frame_len = 4
duration = 0.15
atlas = "Default"

[asset_properties.offset]
horizontal = 24.0
vertical = 48.0
