[meta_properties]
id = "9d17692c87971cd4"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 48]
frame_len = 2
duration = 0.075
atlas = "Default"

[asset_properties.offset]
horizontal = 24.0
vertical = 24.0
