[meta_properties]
id = "ff280fab3533582c"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 64]
frame_len = 6
duration = [0.1, 0.1, 0.25, 0.1, 0.1, 0.2]
atlas = "Default"

[asset_properties.offset]
horizontal = 24.0
vertical = 40.0
