[meta_properties]
id = "91ce59ecce207a71"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 11
duration = [0.1, 0.8, 0.15, 0.1, 0.1, 0.1, 0.2, 0.1, 0.1, 0.1, 1.6]
atlas = "Default"

[asset_properties.offset]
horizontal = "Middle"
vertical = 30.0
