[meta_properties]
id = "78d7c8e38d8b1c15"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 40]
frame_len = 8
duration = 0.175
atlas = "Default"

[asset_properties.offset]
horizontal = 24.0
vertical = 26.0
