[meta_properties]
id = "7d46148ce6f8aec0"
asset_kind = "Animation"

[asset_properties]
frame_size = [64, 88]
frame_len = 4
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 36.0
vertical = 63.0
