[meta_properties]
id = "21a40cc02506a8ec"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 56]
frame_len = 9
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 24.0
vertical = 32.0
