[meta_properties]
id = "a9d772e327ec9a93"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 4
duration = [0.075, 0.075, 0.075, 0.5]
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 30.0
