[meta_properties]
id = "29fc6c6445a46894"
asset_kind = "Animation"

[asset_properties]
frame_size = [24, 24]
frame_len = 8
duration = 0.05
atlas = "Default"

[asset_properties.offset]
horizontal = 12.0
vertical = 20.0
