[meta_properties]
id = "2c1be93d825ba04d"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 40]
frame_len = 4
duration = [0.2, 0.2, 0.45, 0.15]
atlas = "Default"

[asset_properties.offset]
horizontal = 24.0
vertical = 26.0
