[meta_properties]
id = "55ff5c88b05c7e35"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 8
duration = 0.2
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 24.0
