[meta_properties]
id = "cf8b89c0ec6fa488"
asset_kind = "Animation"

[asset_properties]
frame_size = [32, 40]
frame_len = 2
duration = 0.8
atlas = "Default"

[asset_properties.offset]
horizontal = 16.0
vertical = 24.0
