[meta_properties]
id = "36d57dd86825cefd"
asset_kind = "Animation"

[asset_properties]
frame_size = [48, 64]
frame_len = 4
duration = 0.1
atlas = "Default"

[asset_properties.offset]
horizontal = 24.0
vertical = 40.0
